name: Deploy

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Docker Tag
        run: |
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            echo "DOCKER_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          elif [ "$GITHUB_REF_TYPE" = "branch" ] && [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          elif [ "$GITHUB_REF_TYPE" = "branch" ]; then
            echo "DOCKER_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV  # optional fallback
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ezzizzle
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ezzizzle/pyquestions:${{ env.DOCKER_TAG }}
